import { readFileSync, writeFileSync } from 'node:fs';

const { version } = JSON.parse(readFileSync('package.json', 'utf-8'));
writeFileSync(
  'src/version.ts',
  `// generated by prebuild — do not edit manually\nexport const VERSION = ${JSON.stringify(version)};\n`
);
